myfirst/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from music import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/$', views.IndexView.as_view(), name='index'),
    url(r'^music/(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^music/album/add/$', views.AlbumCreate.as_view(), name='album-add'),
    url(r'^music/album/(?P<pk>[0-9]+)/$', views.AlbumUpdate.as_view(), name='album-update'),
    url(r'^music/album/(?P<pk>[0-9]+)/delete/$', views.AlbumDelete.as_view(), name='album-delete'),
    url(r'^register/$', views.UserFormView.as_view(), name='register'),
    url(r'login/', views.UserLogin.as_view(), name='login'),
    url(r'^logout/$', views.LogOut, name='logout'),
    url(r'^music/songs/$', views.SongsIndex.as_view(), name='music_songs'),
    url(r'^music/songs/add$', views.SongCreate.as_view(), name='song-add'),
    url(r'^music/songs/(?P<pk>[0-9]+)$', views.SongUpdate.as_view(), name='song-update'),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

music/models.py
from django.db import models
from django.urls import reverse
# Create your models here.
class Album(models.Model):
    artist = models.CharField(max_length=70)
    album_title = models.CharField(max_length=50)
    genre = models.CharField(max_length=50)
    album_logo = models.FileField()

    def get_absolute_url(self):
        return reverse('detail', kwargs={'pk': self.pk})


    def __str__(self):
        return self.album_title + ' - ' + self.artist


class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=30)
    song_file = models.FileField()

    def get_absolute_url(self):
        return reverse('index')

    def  __str__(self):
        return self.song_title

music/forms.py
from django.contrib.auth.models import User
from django import forms


class UserForm(forms.ModelForm):

    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']


class LoginForm(forms.ModelForm):

    password = forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model=User
        fields=['username', 'password']

music/views.py
from django.views import generic
from django.contrib.auth.models import User
from django.views.generic.edit import CreateView, UpdateView, DeleteView ,View
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse_lazy
from .forms import UserForm,LoginForm
from .models import Album,Song

# ====================Album===============
class IndexView(generic.ListView):
    template_name = 'music/index.html'
    context_object_name = 'all_album'

    def get_queryset(self):
        return Album.objects.all()

class DetailView(generic.DetailView):
    model = Album
    template_name = 'music/details.html'

class AlbumCreate(CreateView):
    model = Album
    fields = ['artist', 'album_title', 'genre', 'album_logo']

class AlbumUpdate(UpdateView):
    model = Album
    fields = ['artist', 'album_title', 'genre', 'album_logo']

class AlbumDelete(DeleteView):
    model = Album
    success_url = reverse_lazy('index')
# ====================================User========================================
class UserFormView(View):
    form_class = UserForm
    template_name = 'music/registration_form.html'

    def get(self, request):

        form = self.form_class(None)

        return render(request, self.template_name,{ 'form':form})

    def post(self, request):

        form = self.form_class(request.POST)

        if form.is_valid():
            user = form.save(commit=False)

            username = form.cleaned_data['username']
            password = form.cleaned_data['password']

            user.set_password(password)

            user.save()


            user = authenticate(username=username,password=password)

            if user is not None:

                if user.is_active:
                    login(request,user)
                    return redirect('index')



        else:
            return render(request, self.template_name, {'form': form})


def LogOut(request):
    form=LoginForm(None)
    logout(request)
    return render(request,'music/login.html',{'form':form})


class UserLogin(View):

    form_class=LoginForm

    template_name='music/login.html'

    def get(self,request):
        form = self.form_class(None)

        return render(request, self.template_name, {'form': form})

    def post(self,request):
            form = self.form_class(None)
            username = request.POST['username']
            password = request.POST['password']

            user=authenticate(username=username,password=password)
            if user is not None:

                if user.is_active:
                    login(request, user)
                    return redirect('index')
            else:
                return render(request, self.template_name, {'form': form})

# ===============================song============================

class SongsIndex(generic.ListView):

    template_name = 'music/song_index.html'
    context_object_name = 'all_music'

    def get_queryset(self):
        return Song.objects.all()


class SongCreate(CreateView):
    model = Song
    fields = ['album','file_type','song_title','song_file']

class SongUpdate(UpdateView):
    model = Song
    fields = ['album', 'file_type', 'song_title', 'song_file']

music/templates/music/album_form.html
{% extends 'music/base.html' %}
{% block title %}Add Album{% endblock %}
{% block body %}
<div class="container">
  <div class="card mx-auto " style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title">Add a Album</h5>
    <h6 class="card-subtitle mb-2 text-muted">Here you can store a new album</h6>
    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {% include 'music/form-template.html' %}
      <div class="form-group">
        <button type="submit" class="btn btn-success">Submit</button>
      </div>
    </form>

  </div>
</div>

</div>
{% endblock %}

music/templates/music/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>{% block title %}Music{% endblock %}</title>
    {% load staticfiles%}
    <link rel="stylesheet" href="{% static 'music/style.css' %}">
      <link href="https://fonts.googleapis.com/css?family=Dancing+Script" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Baloo+Chettan|Raleway" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <script src="http://code.jquery.com/jquery-3.3.1.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </head>
  <body>
  {% block navbar %}
    <!-- =============================navbar================================= -->
    <nav class="navbar sticky-top navbar-expand-lg navbar-dark bg-dark " >
    <!-- ===========logo======== -->
      <a class="navbar-brand" href="{% url 'index' %}">
          <img src="https://image.flaticon.com/icons/png/512/122/122626.png" height="40" width="40">
      </a>
      <!-- ===========logo======== -->
      <!-- =======toggle button====== -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
       <span class="navbar-toggler-icon"></span>
     </button>
     <!-- =======toggle button====== -->
     <!-- ======collaspse=== -->
       <div class="collapse navbar-collapse" id="navbarSupportedContent">
         <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
            <a class="nav-link" href="{% url 'index' %}">
              <i class="fas fa-compact-disc"></i>
              Albums
            </a>
            </li>
            <li class="nav-item active ">
              <a class="nav-link" href="{% url 'music_songs' %}">
                <i class="fas fa-music"></i>
                  Songs
              </a>
            </li>
          </ul>

          <ul class="navbar-nav ">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'album-add' %}">
              <i class="fas fa-plus"></i>
              Add Album
            </a>
          </li>
          <li class="nav-item ">
            <a class="nav-link" href="{% url 'logout' %}">
              <i class="fas fa-power-off"></i>
              Log Out
            </a>
          </li>
          </ul>

      </div>
      <!-- ======collaspse=== -->
    </nav>
    {% endblock %}
    <!-- =============================navbar================================= -->
    {% block body %}
    {% endblock %}

  </body>
</html>

music/templates/music/details.html
{% extends 'music/base.html' %}
{% block title %}Album Detail{% endblock %}
{% block body %}
<div class="row">
    <div class="col-3">


      <img src="{{album.album_logo.url}}" height="420" width="420">
      <h1>{{album.album_title}}</h1>
      <h2>{{album.artist}}</h2>
    </div>


<div class= "col-7">
  <div class="container">


  <form style="display:inline;" action="{% url 'detail' album.id %}" method="get">
    <button type="submit" class="btn btn-outline-primary" >View All</button>
  </form>
  <form style="display:inline;"  action="{% url 'song-add' %}" method="get">
    <button type="submit" class="btn btn-outline-primary" >Add New Song</button>
  </form>
  </div>
<div class="nut">
<h1>All Songs</h1>
<table>
  <thead>
    <tr>
      <th colspan="3">Title</th>
    </tr>
  </thead>
<tbody>

</tbody>

  {% for song in album.song_set.all %}

  <tr>
    <td><hr class="style-five" ></td>
    <td colspan="3">{{song.song_title}}</td>
    <td colspan="3" >
      <form class="woss1" action="{{song.song_file.url}}" method="get">
        <button type="submit" class="btn btn-success"><i class="fas fa-play"></i>play</button>
      </form>
    </td>
  </tr>
  {% endfor %}
</table>
</div>
</div>
</div>
{% endblock %}

music/templates/music/form-template.html
{% for field in form %}
<div class="form-group ">



  <label >{{ field.label_tag }}</label>
  <div class="col-10">
    {{ field }}

  </div>


</div>
{% endfor %}

music/templates/music/index.html
{% extends 'music/base.html' %}
{% block title %}Albums{% endblock %}
{% block body %}
{% if all_album %}

    <div class="row">
  {%for album in all_album %}
    <div class="col-3">


    <a href="{% url 'detail' album.id %}"><img src="{{album.album_logo.url}}" height="420" width="460" ><br></a><h2>{{album.album_title}}</h2><br><h3>{{album.artist}}</h3><br>
    <form style="display:inline;" method="get" action="{% url 'detail' album.id %}">
    <button class="btn btn-primary" type="submit">View details</button>
    </form>
    <form style="display:inline;"  method="post" action="{% url 'album-update' album.id %}">
      {% csrf_token %}
    <button class="btn btn-secondary" type="submit"><i class="fas fa-pencil-alt"></i></button>
    </form>
    <form style="display:inline;"  method="post" action="{% url 'album-delete' album.id %}">
         {% csrf_token %}
    <button class="btn btn-secondary" type="submit"><i class="fas fa-trash-alt"></i></button>
    </form>
    </div>
  {%endfor%}
    </div>

{% else %}
  <h3>there are No Albums</h3>
{% endif %}
{% endblock %}

music/templates/music/login.html
{% extends 'music/base.html' %}
{% block title %}Login{% endblock %}
{% block navbar %} {% endblock %}
{% block body %}
<div class="container">
    <div class="card mx-auto" style="width: 40rem;">
      <div class="card-body">
        <h5 class="card-title"><p style="font-family: 'Dancing Script', cursive;font-size:80px"><img src="https://image.flaticon.com/icons/png/512/122/122626.png" height="80" width="80">Open Cloud </p></h5>
        <h6 class="card-subtitle mb-2 text-muted">Your Music Storage Cloud </h6>
        <p class="card-text">In open cloud you can store your music over a server for free.It gives you personalized music services and user friendly interface.If you are a registered user Log in. Or register if you are not</p>
          <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
              {% csrf_token %}
            {% include 'music/form-template.html' %}
      <div class="form-group">
        <button type="submit" class="btn btn-success">Log in</button> <a href="{% url 'register' %}" class="card-link">Register</a>
      </div>

    </form>
      </div>
    </div>
</div>
{% endblock %}

music/templates/music/registration_form.html
{% extends 'music/base.html' %}
{% block title %}Create an account{% endblock %}
{% block navbar %}{% endblock %}
{% block body %}
<div class="container">
  <div class="card mx-auto " style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title">Create an account</h5>
    <h6 class="card-subtitle mb-2 text-muted">Here you have to create an account</h6>
    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {% include 'music/form-template.html' %}
      <div class="form-group">
        <button type="submit" class="btn btn-success">Submit</button>
      </div>
    </form>

  </div>
</div>

</div>
{% endblock %}

music/templates/music/song_form.html
{% extends 'music/base.html' %}
{% block title %}Add Song{% endblock %}
{% block body %}
<div class="container">
  <div class="card mx-auto " style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title">Add a Song</h5>
    <h6 class="card-subtitle mb-2 text-muted">Here you can store a new song</h6>
    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {% include 'music/form-template.html' %}
      <div class="form-group">
        <button type="submit" class="btn btn-success">Submit</button>
      </div>
    </form>

  </div>
</div>

</div>
{% endblock %}

music/templates/music/song_index.html
{% extends 'music/base.html' %}
{% block title %}Song Detail{% endblock %}
  {% block body %}
<div class="container">
    <div class="card">
  <div class="card-header">
    Featured
  </div>
  <div class="card-body">
    <h5 class="card-title"><p style="font-family: 'Dancing Script', cursive;font-size:80px">Songs</p></h5>
    <p class="card-text">Here are your All of Your songs </p>
       <ul class="list-group list-group-flush">
           {% if all_music is None %}
           <h3>there are No Albums</h3>
           {% else%}
           {% for song in all_music %}
            <li class="list-group-item">{{song.album}}:{{song.song_title}}   -

                <form style="display:inline;" action="{{ song.song_file.url }}" method="get">
                    <button type="submit" class="btn btn-success"><i class="fas fa-play"></i>play</button>
                </form>
                <form style="display:inline;"  method="post" action="{% url 'song-update' song.pk  %}">
                    {% csrf_token %}
                     <button class="btn btn-secondary" type="submit"><i class="fas fa-pencil-alt"></i></button>
                     </form>
            </li>
           {% endfor %}
           {% endif%}

       </ul>
  </div>
</div>
    </div>
    {% endblock %}